baseURL = 'https://f2rp.bgforge.net/'
languageCode = 'en-us'
title = 'Fallout 2 Restoration Project Walkthrough'

[module]
  [[module.imports]]
    path = 'github.com/alex-shpak/hugo-book'

[params]
  BookFavicon = '/favicon.ico'
  BookTheme = 'auto'
  BookToC = true
  BookSection = '/'
  BookRepo = 'https://github.com/BGforgeNet/f2rp-walkthrough'
  BookEditLink = 'https://github.com/BGforgeNet/f2rp-walkthrough/edit/master/{{ .Path }}'

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      typographer = false
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3

[menu]
  [[menu.after]]
    name = "World Map"
    url = "/map/"
    weight = 1
